### ISSUE TITLE
No Stream method

### ISSUE THREAD

**Issue by kcswag** [cohere-ai/cohere-go#53]
There is no Stream method for cohere client

**Comment by Mr-Destructive** [comment]
The release tags have been out of order, so it is causing a few issues. The release `v1.2.2` was made on `August 2022` which is the highest version number among the releases. The current release tag is `v0.2.0` which is not the greater number. Hence most of the features and source code being packaged are from the release `v1.2.2` and not the latest to date.

So, this can be fixed by changing the release tags to `v1.2.3` or `v2.0.0` as per the maintainer's preferences.
Thank you for creating this package.
